export const GET_MENTORS = 'GET_MENTORS';
export const FAILURE_GET_MENTORS = 'FAILURE_GET_MENTORS';
export const SUCCESS_GET_MENTORS = 'SUCCESS_GET_MENTORS';

export const CREATE_MENTOR = 'CREATE_MENTOR';
export const SUCCESS_CREATE_MENTOR = 'SUCCESS_CREATE_MENTOR';
export const FAILURE_CREATE_MENTOR = 'FAILURE_CREATE_MENTOR';

export const DELETE_MENTOR = 'DELETE_MENTOR';
export const SUCCESS_DELETE_MENTOR = 'SUCCESS_DELETE_MENTOR';
export const FAILURE_DELETE_MENTOR = 'FAILURE_DELETE_MENTOR';

export const UPDATE_MENTOR = 'UPDATE_MENTOR';
export const SUCCESS_UPDATE_MENTOR = 'SUCCESS_UPDATE_MENTOR';
export const FAILURE_UPDATE_MENTOR = 'FAILURE_UPDATE_MENTOR';

export const SEARCH_LESSONS = 'SEARCH_LESSONS';
export const SUCCESS_SEARCH_LESSONS = 'SUCCESS_SEARCH_LESSONS';
export const FAILURE_SEARCH_LESSONS = 'FAILURE_SEARCH_LESSONS';

export const AUTO_COMPLETE = 'AUTO_COMPLETE';
export const SUCCESS_AUTO_COMPLETE = 'SUCCESS_AUTO_COMPLETE';
export const FAILURE_AUTO_COMPLETE = 'FAILURE_AUTO_COMPLETE';

export const GET_ACTIVE_GROUPS = 'GET_ACTIVE_GROUPS';
export const FAILURE_GET_ACTIVE_GROUPS = 'FAILURE_GET_ACTIVE_GROUPS';
export const SUCCESS_GET_ACTIVE_GROUPS = 'SUCCESS_GET_ACTIVE_GROUPS';

export const GET_GROUPS = 'GET_GROUPS';
export const FAILURE_GET_GROUPS = 'FAILURE_GET_GROUPS';
export const SUCCESS_GET_GROUPS = 'SUCCESS_GET_GROUPS';

export const CREATE_GROUP = 'CREATE_GROUP';
export const FAILURE_CREATE_GROUP = 'FAILURE_CREATE_GROUP';
export const SUCCESS_CREATE_GROUP = 'SUCCESS_CREATE_GROUP';

export const DELETE_GROUP = 'DELETE_GROUP';
export const SUCCESS_DELETE_GROUP = 'SUCCESS_DELETE_GROUP';
export const FAILURE_DELETE_GROUP = 'FAILURE_DELETE_GROUP';

export const UPDATE_GROUP = 'UPDATE_GROUP';
export const SUCCESS_UPDATE_GROUP = 'SUCCESS_UPDATE_GROUP';
export const FAILURE_UPDATE_GROUP = 'FAILURE_UPDATE_GROUP';

export const CREATE_LESSON_IN_WEEK = 'CREATE_LESSON_IN_WEEK';
export const FAILURE_CREATE_LESSON_IN_WEEK = 'FAILURE_CREATE_LESSON_IN_WEEK';
export const SUCCESS_CREATE_LESSON_IN_WEEK = 'SUCCESS_CREATE_LESSON_IN_WEEK';

export const GET_ROOMS = 'GET_ROOMS';
export const FAILURE_GET_ROOMS = 'FAILURE_GET_ROOMS';
export const SUCCESS_GET_ROOMS = 'SUCCESS_GET_ROOMS';

export const GET_COURSES = 'GET_COURSES';
export const FAILURE_GET_COURSES = 'FAILURE_GET_COURSES';
export const SUCCESS_GET_COURSES = 'SUCCESS_GET_COURSES';